/* eslint-disable @typescript-eslint/no-unused-vars */
import { CircularProgress } from "@mui/material";
import AppContext from "@store/index";
import { useSession } from "next-auth/react";
import Head from "next/head";
import React, { useContext, useEffect } from "react";

interface AppLayoutProps {
  title?: string;
  children?: React.ReactNode;
}

const AppLayout: React.FC<AppLayoutProps> = ({ title, children }) => {
  const { data: session, status } = useSession();
  const { state, dispatch } = useContext(AppContext);

  useEffect(() => {
    console.log(session);
    if (status === "authenticated") {
      dispatch({
        type: "SET_AUTH",
        payload: true,
      });
      dispatch({
        type: "SET_SESSION",
        payload: session.id,
      });
    }
  }, [dispatch, session, status]);

  return (
    <>
      <Head>
        <title>Simba - Cal.com {title ? `| ${title}` : ""} </title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"></meta>
        <meta name="description" content="Simba genesis" />
        <meta
          name="keywords"
          content="simba genesis, cal.com, next js, javascript, emmanuel popoola, eclipse"
        />
        <meta name="author" content="eclipse_cmd" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {status === "authenticated" ? (
        <main className="min-h-screen bg-gray-100">{children}</main>
      ) : (
        <>
          <div className="relative flex items-center justify-center min-w-full min-h-screen">
            <CircularProgress size={24} style={{ color: "#000000" }} />
          </div>
        </>
      )}
    </>
  );
};

export default AppLayout;
