import Head from "next/head";
import React from "react";

interface PublicLayoutProps {
  title?: string;
  children?: React.ReactNode;
}

const PublicLayout: React.FC<PublicLayoutProps> = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>Simba - Cal.com {title ? `| ${title}` : ""} </title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"></meta>
        <meta name="description" content="Simba genesis" />
        <meta
          name="keywords"
          content="simba genesis, cal.com, next js, javascript, emmanuel popoola, eclipse"
        />
        <meta name="author" content="eclipse_cmd" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="bg-gray-100">{children}</main>
    </>
  );
};

export default PublicLayout;
